version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Build
          command: cd projet_maven && mvn -B -DskipTests clean package
      - run:
          name: Test
          command: cd projet_maven && mvn test
      - codecov/upload
      - run:
          name: CheckStyle
          command: cd projet_maven && mvn checkstyle:checkstyle

workflows:
  mattia-maven-workflow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - master

        
    
