version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Move in the good directory
          command: cd projet_maven
      - run:
          name: Check directory
          command: echo "$PWD"
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

workflows:
  mattia-maven-workflow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - master

        
    
