version: 2.1

orbs:
  maven: circleci/maven@1.3
jobs:
  mattia:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Mattia"
          command: "echo je suis Mattia ! "

workflows:
  mattia_maven_test:
    jobs:
      - mattia
      - maven/test: # checkout, build, test, and upload test results
        filters:
          branches:
            only:
              - master
        
    
