version: 2.1

orbs:
  maven: circleci/maven@1.3.0

workflows:
    mattia-maven-test:
      jobs:
        - maven/test:
            app_src_directory: projet_maven 
            test_results_path: projet_maven/target/surefire-reports
            filters:
              branches:
                only:
                  - master

        
    
